sandbox:
  target: local
  outputs:
    local:
      type: bigquery
      method: service-account
      keyfile: /Users/ashyam/Documents/GitHub/pulse-client-template/keyfile.json
      project: insightsprod
      execution_project: insightsprod
      dataset: sandbox_0000_local
      location: us-central1
      threads: 24
      retries: 1
    dev:
      type: bigquery
      method: service-account
      keyfile: /opt/airflow/dags/keyfile.json
      project: insightsprod
      execution_project: insightsprod
      dataset: sandbox_0000_dev
      location: us-central1
      threads: 24
      retries: 1
    prod:
      type: bigquery
      method: service-account
      keyfile: /opt/airflow/dags/keyfile.json
      project: insightsprod
      execution_project: insightsprod
      dataset: sandbox_0000_prod
      location: us-central1
      threads: 24
      retries: 1